# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fa9674ca7c48622134ad6cb4186b5e71b2f00d9467beff5b5149ba8d0efd0f9a56d7a4ad4cd11d047b2830754a7234ec9b87f9eddcc0b3b2b70b9a0bf845d9e

test:
  secret_key_base: 6e1d9e71721d37fe71d8f98cb3de4d28d1b94a50b05a72b27e5454d9b7cf6692218355b0c741615ba38abea588e3a4d4f895555fa8f57326234c4ccd262b0d88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
